import { StateGraph, StateSchema, START, END, type GraphNode, type CompiledStateGraph } from "@langchain/langgraph"
import * as z from "zod";
import { createAgent, HumanMessage, providerStrategy, toolStrategy } from "langchain"
import { cohereModel, geminiModel, mistralAIModel } from "./model.ai.ts";

// providerStrategy used to generate formatted output with gemini
// We use toolStrategy for other LLMs


const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge_response: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})

const solution_node: GraphNode<typeof state> = async (state) => {
    const userPrompt = state.problem;
    const [solution_1, solution_2] = await Promise.all([
        mistralAIModel.invoke(userPrompt), cohereModel.invoke(userPrompt)
    ])
    return {
        solution_1: solution_1.text,
        solution_2: solution_2.text,
    }
}
const judge_res_format = z.object({
    solution_1_score: z.number().min(0).max(10),
    solution_2_score: z.number().min(0).max(10),
    solution_1_reasoning: z.string(),
    solution_2_reasoning: z.string(),
})
const judge_node: GraphNode<typeof state> = async (state) => {
    const { solution_1, solution_2, problem } = state
    const judgeAgent = createAgent({
        model: geminiModel,
        tools: [],
        responseFormat: providerStrategy(judge_res_format),
        systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
    })
    const judgeResponse = await judgeAgent.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `)
        ]
    })
    const { solution_1_score, solution_1_reasoning, solution_2_score, solution_2_reasoning } = judgeResponse.structuredResponse!;
    return {
        judge_response: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning,
        }
    }
}

const graph = new StateGraph(state)
    .addNode("solution_node", solution_node)
    .addNode("judge_node", judge_node)
    .addEdge(START, "solution_node")
    .addEdge("solution_node", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default graph
