import { StateGraph, StateSchema, START, END, type GraphNode, type CompiledStateGraph } from "@langchain/langgraph"
import * as z from "zod";
import { createAgent, HumanMessage, providerStrategy, toolStrategy } from "langchain"
import { cohereModel, geminiModel, mistralAIModel } from "./model.ai.ts";

// providerStrategy used to generate formatted output with gemini
// We use toolStrategy for other LLMs

const judge_res_format = z.object({
    solution_1_score: z.number().min(0).max(10),
    solution_2_score: z.number().min(0).max(10),
    solution_1_reasoning: z.string(),
    solution_2_reasoning: z.string(),
})
const state = new StateSchema({
    prompt: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    retryCount: z.number().default(0),
    isValid: z.boolean().default(false),
    isJudgeValid: z.boolean().default(false),
    judge_response: judge_res_format,
    judgeRetryCount: z.number().default(0),
    judgeSuccess: z.boolean().default(false),
})


const judgeAgent = createAgent({
    model: geminiModel,
    responseFormat: providerStrategy(judge_res_format),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
})
const solution_node: GraphNode<typeof state> = async (state) => {
    const userPrompt = state.prompt;
    // try {
    //     const [solution_1, solution_2] = await Promise.all([
    //         mistralAIModel.invoke(userPrompt), cohereModel.invoke(userPrompt)
    //     ])
    //     return {
    //         solution_1: solution_1.text,
    //         solution_2: solution_2.text,
    //     }

    // } catch (error) {
    //     console.log(error);
    //     return {
    //         solution_1: "",
    //         solution_2: ""
    //     }
    // }

    const [mistralResult, cohereResult] =
        await Promise.allSettled([
            mistralAIModel.invoke(userPrompt),
            cohereModel.invoke(userPrompt),
        ]);

    return {
        solution_1:
            mistralResult.status === "fulfilled"
                ? mistralResult.value.text
                : "",

        solution_2:
            cohereResult.status === "fulfilled"
                ? cohereResult.value.text
                : "",
    };

}

const validation_node: GraphNode<typeof state> = async (state) => {
    const valid =
        state.solution_1.trim().length > 0 &&
        state.solution_2.trim().length > 0;
    return {
        isValid: valid
    }

}
const retryNode: GraphNode<typeof state> = async (state) => {
    return {
        retryCount: state.retryCount + 1
    }

}
const judge_node: GraphNode<typeof state> = async (state) => {
    const { solution_1, solution_2, prompt } = state
    try {
        const response = await judgeAgent.invoke({
            messages: [
                new HumanMessage(`
               Problem:
                ${prompt}

                Solution 1:
                ${solution_1}

                Solution 2:
                ${solution_2}

                Evaluate both independently.
                Score each between 0 and 10.
Give concise reasoning.
                `)
            ]
        });

        return {
            judge_response: response.structuredResponse!,
            judgeSuccess: true,
        };

    } catch (err) {
        console.log("Judge Failed");

        return {
            judgeSuccess: false,
        };
    }
}


const graph = new StateGraph(state)
    .addNode("solution_node", solution_node)
    .addNode("validation_node", validation_node)
    .addNode("retry_node", retryNode)
    .addNode("judge_node", judge_node)
    .addEdge(START, "solution_node")
    .addEdge("solution_node", "validation_node")
    .addConditionalEdges(
        "validation_node",
        (state) => {
            if (state.isValid) {
                return "judge_node";
            }
            return "retry_node";
        }
    )
    .addConditionalEdges(
        "retry_node",
        (state) => {
            if (state.retryCount >= 3) {
                return END;
            }
            return "solution_node";
        }
    )
    .addEdge("judge_node", END)
    .compile()

export default graph
